using System.Security.Cryptography;
using System.Text.Json.Nodes;

namespace KspContinuum.Tools;

internal static class LifecycleReportCommand
{
    public static int Run(string[] args) { var a = new Arguments(args); var input = a.Required("--input"); var output = a.Required("--output"); var raw = File.ReadAllBytes(input); Tooling.Require(raw.Length <= 4 * 1024 * 1024, "input exceeds 4 MiB"); var data = JsonNode.Parse(raw) as JsonObject ?? throw new ToolException("expected JSON object"); var result = Summarize(data); result["sourceSha256"] = Convert.ToHexString(SHA256.HashData(raw)).ToLowerInvariant(); Tooling.WriteJsonNew(output, result); return 0; }
    private static JsonObject Summarize(JsonObject data)
    {
        Tooling.Require(data["schema"]?.ToString() == "ksp-continuum-lifecycle-trace/v1", "unsupported schema"); Tooling.Require(data["physicsWrites"]?.GetValue<bool>() == false && data["installedOrderQualified"]?.GetValue<bool>() == false, "unsupported authority claim"); var events = data["events"] as JsonArray ?? throw new ToolException("invalid events"); Tooling.Require(events.Count <= 8192 && data["completedEvents"]?.GetValue<int>() == events.Count, "event count mismatch"); var stageCounts = new SortedDictionary<string, int>(); var groups = new SortedDictionary<long, JsonArray>(); int parts = 0, holders = 0; long? thread = null;
        for (var i = 0; i < events.Count; i++) { var e = events[i] as JsonObject ?? throw new ToolException("invalid event"); var c = e["context"] as JsonObject ?? throw new ToolException("invalid context"); Tooling.Require(c["sequence"]?.GetValue<int>() == i + 1, "noncontiguous sequence"); var current = c["threadId"]?.GetValue<long>() ?? throw new ToolException("missing thread"); Tooling.Require(thread is null || thread == current, "mixed observer threads"); thread = current; var stage = Tooling.Text(c["stage"], "stage"); stageCounts[stage] = stageCounts.GetValueOrDefault(stage) + 1; var host = c["hostFixedObservations"]?.GetValue<long>() ?? 0; if (!groups.TryGetValue(host, out var group)) { group = []; groups.Add(host, group); } group.Add(stage); var samples = e["parts"] as JsonArray ?? throw new ToolException("invalid parts"); parts += samples.Count; foreach (var sample in samples.Cast<JsonObject>()) { var census = sample["census"] as JsonObject ?? throw new ToolException("invalid census"); holders += (census["forces"] as JsonArray)?.Count ?? throw new ToolException("invalid forces"); } }
        Tooling.Require(data["retainedParts"]?.GetValue<int>() == parts && data["retainedHolders"]?.GetValue<int>() == holders, "retained count mismatch"); var variants = groups.Values.GroupBy(x => string.Join("\0", x.Select(n => n!.ToString()))).Select(g => new JsonObject { { "stages", new JsonArray(g.First().Select(x => JsonValue.Create(x!.ToString())).ToArray()) }, { "groupCount", g.Count() } }).ToArray();
        var result = new JsonObject { { "schema", "ksp-continuum-lifecycle-summary/v1" }, { "detail", data["detail"]?.DeepClone() }, { "physicsWrites", false }, { "installedOrderQualified", false }, { "physicsStepGroupingQualified", false }, { "validation", "bounded receipt structure and observed counters; not installed behavior" }, { "threadId", thread }, { "elapsedWallSeconds", data["elapsedWallSeconds"]?.DeepClone() }, { "observedEvents", events.Count }, { "skippedArmingCallbacks", data["skippedArmingCallbacks"]?.DeepClone() }, { "hostFixedObservations", data["hostFixedObservations"]?.DeepClone() }, { "retainedParts", parts }, { "retainedHolders", holders }, { "declaredEncodedEventBytes", data["encodedEventBytes"]?.DeepClone() }, { "generationTotals", new JsonObject { { "topologyGeneration", data["topologyGeneration"]?.DeepClone() }, { "frameGeneration", data["frameGeneration"]?.DeepClone() }, { "originEvents", data["originEvents"]?.DeepClone() } } }, { "stageCounts", new JsonObject(stageCounts.Select(x => KeyValuePair.Create<string, JsonNode?>(x.Key, x.Value))) }, { "hostObservationGroups", new JsonArray(groups.Select(x => (JsonNode)new JsonObject { { "hostFixedObservation", x.Key }, { "stages", x.Value } }).ToArray()) }, { "observedOrderVariants", new JsonArray(variants) }, { "unavailableForceSources", new JsonArray("gravity", "stock-aerodynamics", "contact-impulses", "direct-rigidbody-writes") } };
        foreach (var key in new[] { "sessionId", "nativeAssemblyMvid", "unityAssemblyMvid", "pluginAssemblyMvid", "evidence", "status", "cleanupStatus", "forceScope", "orderingScope" }) result[key] = data[key]?.DeepClone(); return result;
    }
}
